set_discharge_time:
  name: Set Discharge Time
  description: Set the end discharge time for the battery
  fields:
    end_discharge:
      name: End Discharge Time
      description: The time when battery discharge should end (format HH:MM)
      example: "23:00"
      required: true
      selector:
        time: {}

set_discharge_start_time:
  name: Set Discharge Start Time
  description: Set the start time for battery discharge (time_disf1a)
  fields:
    start_discharge:
      name: Start Discharge Time
      description: The time when battery discharge should start (format HH:MM)
      example: "17:00"
      required: true
      selector:
        time: {}

set_discharge_end_time:
  name: Set Discharge End Time
  description: Set the end time for battery discharge (time_dise1a)
  fields:
    end_discharge:
      name: End Discharge Time
      description: The time when battery discharge should end (format HH:MM)
      example: "23:00"
      required: true
      selector:
        time: {}

set_grid_charge_start_time:
  name: Set Grid Charge Start Time
  description: Set the start time for grid charging (time_chaf1a)
  fields:
    start_grid_charge:
      name: Start Grid Charge Time
      description: The time when grid charging should start (format HH:MM)
      example: "01:00"
      required: true
      selector:
        time: {}

set_grid_charge_end_time:
  name: Set Grid Charge End Time
  description: Set the end time for grid charging (time_chae1a)
  fields:
    end_grid_charge:
      name: End Grid Charge Time
      description: The time when grid charging should end (format HH:MM)
      example: "06:00"
      required: true
      selector:
        time: {}
